version: '3.5'

services:
    client:
        container_name: client-dev
        build: ./client/.
        ports:
            - 3000:3000
        volumes:
            - ./client/public:/app/public
            - ./client/src:/app/src
        links: 
            - server:server
        networks:
            - dev-network
        working_dir: /app
        stdin_open: true
        command: yarn start

    server:
        container_name: server-dev
        build: ./server/.
        user: node
        volumes:
            - ./server/src:/home/node/src
        networks:
            - dev-network
        working_dir: /home/node
        command: yarn run dev

networks:
    dev-network:
        name: react-node-dev