version: '3.5'

services:
    server:
        container_name: server-prod
        build: ./server/.
        user: node
        volumes:
            - ./server/src:/home/node/src
            - ./server/build:/home/node/build
        ports:
            - 3003:3001
        networks:
            - prod-network
        working_dir: /home/node
        command: yarn start

networks:
    prod-network:
        name: react-node-prod