version: '3.5'

services:
    server:
        container_name: server-prod
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        image: react-node_server:prod
        user: node
        ports:
            - 3003:3001
        networks:
            - prod-network
        working_dir: /home/node
        command: yarn start

networks:
    prod-network:
        name: react-node-prod